### ISSUE TITLE
💡 [REQUEST] - Display CYCID next to the user name

### ISSUE THREAD

**Issue by yuenci** [fgacyc/erp#12]
### Summary
 Some staff want to know their cycid, they don't have a place to check it so we need:
 Display CYCID next to the user name
 
 

### Basic Example

![image](https://github.com/fgacyc/erp/assets/33682384/e0e1b9d9-3c5e-43b1-9efe-bad37fefe70d)

### General things to do

- [x] Get CYCID from indexDB
- [x] Use flex layout show username and CYCID

**Comment by Dorothea303** [comment]
@ETCasual hey bro just to double check. This ticket is waiting for you to merge then it will be move to done right ?

**Comment by ETCasual** [comment]
yes, when the merge is done is will be automated to Done

**Comment by Dorothea303** [comment]
Ok great thanks bro
