### ISSUE TITLE
💡 [REQUEST] - Pastoral Members management

### ISSUE THREAD

**Issue by yuenci** [fgacyc/erp#29]
### Summary

A subsection to manage user related functions for admin

### Basic Example

None

### General things to do

- [x]  Ministry Member CRUD
- [x]  Role change

**Comment by yuenci** [comment]
This feature belongs to this menu item:
![image](https://github.com/fgacyc/erp/assets/33682384/f0ab4650-809a-4389-8a19-69a7d96587d0)

**Comment by Dorothea303** [comment]
Hi guys, can i have an update progress on this ticket? @ETCasual  @JayChew

**Comment by ETCasual** [comment]
Was working on `Leaders' Retreat` stuff and as this was encountering bugs so this was put on hold, but now it was resumed, Pastoral's `Create`, `Read`, `Update` and `Delete` are all there already, however the issue is `Roles` now, under users.

**Comment by Dorothea303** [comment]
Thanks for the update, I'll try to meet up with phoebe and discuss further on this. In the meantime, is there any info you need from admin side?
