### ISSUE TITLE
💡 [REQUEST] - Migration to TS

### ISSUE THREAD

**Issue by ETCasual** [fgacyc/erp#7]
### Summary

Currently there is issues and development blockers from developing in JS due to code standards and not knowing types and dealing with types properly. There is an urgent need to transition to TypeScript for better development experience and buildtime error checkings.

### Basic Example

-

### General things to do

- [x] Convert to TS

**Comment by Dorothea303** [comment]
Pending response : Do let me know by the end of today whether or not you need me to assign someone to assist you on this task. @ETCasual
